INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (1, 'Spring roll z krewetkami', 'Спринг-ролл с тигровой креветкой', 'Spring roll with tiger shrimp', 'Спрінг-рол з тигровою креветкою', 60, 1, 5, 0.27, 'Spring_roll_with_shrimp', 'uploads/2023/files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (2, 'Set z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 2, 8, 0.27, 'Set_roll_with_shrimp', 'uploads/2023/files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (3, 'Baked something', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 3, 7, 0.27, 'Baked_something', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (4, 'Sushi z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 4, 9, 0.27, 'Sushi_with_shrimp', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (5, 'Sushi-Cake z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 5, 7, 0.27, 'Sushi-Cake z krewetkami', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (6, 'Futomaki z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 6, 1, 0.27, 'Futomaki_with_shrimp', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (7, 'Salad z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 7, 8, 0.27, 'Salad_with_shrimp', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (8, 'Bowl z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 8, 2, 0.27, 'Bowl_with_shrimp', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (9, 'Dessert z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 9, 3, 0.27, 'Dessert_with_shrimp', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (10, 'Drink z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 10, 1, 0.27, 'Drink_with_shrimp', 'uploads/mock-2023/files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (11, 'Spring roll2 z krewetkami', 'Спринг-ролл с тигровой креветкой', 'Spring roll with tiger shrimp', 'Спрінг-рол з тигровою креветкою', 60, 1, 5, 0.27, 'Spring_roll_with_shrimp', 'uploads/2023/files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (12, 'Set2 z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 2, 8, 0.27, 'Set_roll_with_shrimp', 'uploads/2023/files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (13, 'Set3 z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 2, 8, 0.27, 'Set_roll_with_shrimp', 'uploads/2023/files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (14, 'Baked2 something', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 3, 7, 0.27, 'Baked_something', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (15, 'Baked3 something', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 3, 7, 0.27, 'Baked_something', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (16, 'Baked4 something', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 3, 7, 0.27, 'Baked_something', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (17, 'Sushi2 z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 4, 9, 0.27, 'Sushi_with_shrimp', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (18, 'Sushi3 z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 4, 9, 0.27, 'Sushi_with_shrimp', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (19, 'Sushi4 z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 4, 9, 0.27, 'Sushi_with_shrimp', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);

INSERT INTO product (id, name, name_ru, name_en, name_ua, price, category_id, allergens_id, weight, url, img, status, description, description_ru, description_en, description_ua, size, sale, cart_count, sort, box, removal_date )
VALUES (20, 'Sushi5 z krewetkami', 'MockedLocalizeRu', 'MockedLocalizeEn' , 'MockedLocalizeUa', 60, 4, 9, 0.27, 'Sushi_with_shrimp', 'uploads/2023/mock-files-1683805117204.jpg', 1, '<p>Papier ryżowy</p><p>Liscie salaty</p><p>Ser philadelphia</p><p>Ogórek</p><p>Tobiko</p><p>Krewetka</p><p>Sos Teriyaki</p>', '<p>Рисовая бумага</p><p>Листья салата</p><p>Сыр Филадельфия</p><p>Огурец</p><p>Тобико</p><p>Креветка</p><p>Соус терияки</p>', '<p>Rice paper</p><p>Salata leaves</p><p>Philadelphia cheese</p><p>Cucumber</p><p>Tobiko</p><p>Prawn</p><p>Teriyaki sauce</p>', '<p>Рисовий папір</p><p>Листя салату</p><p>Сир Філадельфія</p><p>Огірок</p><p>Тобіко</p><p>Креветка</p><p>Соус Теріякі</p>', 4, 0, 4, 2, 1, null);
