# This is workflow to automatically deploy on server.

name: "CD"
env:
  CURRENT_BRANCH : ${{ github.ref_name }}
  DOCKER_VERSION : ${{ github.event.workflow_run.head_sha }}

on:
  push:
    branches:
      - 'develop'
      - 'stage'
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "CD"
  CD:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.CURRENT_BRANCH }}
      # Login into our docker registry.
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Runs a single command using the runners shell.
      - name: Build & push docker DEVELOP images to our server
        if: env.CURRENT_BRANCH == 'develop'
        run: make docker ENVIRONMENT=develop

      - name: Deploy DEVELOP environment images
        uses: appleboy/ssh-action@master
        if: env.CURRENT_BRANCH == 'develop'
        with:
          host:       ${{ secrets.SSH_HOST_DEVELOP }}
          port:       ${{ secrets.SSH_PORT }}
          username:   ${{ secrets.SSH_USERNAME }}
          key:        ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ${{ secrets.PROJECT_PATH_DEVELOP }}
            /bin/bash redeploy.sh 

      # Runs a single command using the runners shell.
      - name: Build & push docker STAGE images to our server
        if: env.CURRENT_BRANCH == 'stage'
        run:  make docker ENVIRONMENT=stage

      - name: Deploy STAGE environment images
        uses: appleboy/ssh-action@master
        if: env.CURRENT_BRANCH == 'stage'
        with:
          host:       ${{ secrets.SSH_HOST_STAGE }}
          port:       ${{ secrets.SSH_PORT }}
          username:   ${{ secrets.SSH_USERNAME }}
          key:        ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ${{ secrets.PROJECT_PATH_STAGE }}
            /bin/bash redeploy.sh

          # Runs a single command using the runners shell.
      - name: Build & push docker PROD images to our server
        if: env.CURRENT_BRANCH == 'prod'
        run:  make docker ENVIRONMENT=prod

      - name: Deploy PROD environment images
        uses: appleboy/ssh-action@master
        if: env.CURRENT_BRANCH == 'prod'
        with:
          host:       ${{ secrets.SSH_HOST_PROD }}
          port:       ${{ secrets.SSH_PORT }}
          username:   ${{ secrets.SSH_USERNAME }}
          key:        ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ${{ secrets.PROJECT_PATH_PROD }}
            /bin/bash redeploy.sh
